org: kwanjichoi
app: gpt-lambda
service: gpt-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action: 
              - 'lambda:InvokeFunction'
              - 'lambda:GetFunction'
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:ListBucket'
          Resource: '*'

plugins:
  - serverless-python-requirements
  # Set env variables from .env file
  - serverless-dotenv-plugin

# for Non-pure python packages like pynum
custom:
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile
    slim: true
    zip: true

functions:
  gpt:
    handler: handler.handler
    ephemeralStorageSize: 10240
    timeout: 29
    events:
      - httpApi:
          path: /slack/events
          method: post
